from enum import Enum

class CallState(str, Enum):
	START = "START"
	
	FMCSA_PENDING = "FMCSA_PENDING"
	OTP_PENDING = "OTP_PENDING"
	VERIFIED = "VERIFIED"

	LOAD_SEARCH = "LOAD_SEARCH"
	LOAD_PRESENTED = "LOAD_PRESENTED"

	NEGOTIATING = "NEGOTIATING"
	BOOKING = "BOOKING"
	HANDOFF = "HANDOFF"


	COMPLETE = "COMPLETE"
	FAILED = "FAILED"